---
name: lint
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      codename:
        required: true
        type: string
      docker_image_name:
        required: true
        type: string
      docker_image_tag:
        required: true
        type: string

jobs:
  list_spec_files:
    runs-on: ubuntu-24.04
    outputs:
      spec_files: ${{ steps.list_spec_files.outputs.spec_files }}
    steps:
      - uses: actions/checkout@v5
      - id: list_spec_files
        env:
          CODENAME: ${{ inputs.codename }}
        run: |
          spec_files=$(find "SPECS/${CODENAME}" -type l -name '*.spec' -printf '%f\n' | jq --raw-input . | jq --compact-output --slurp .)
          echo "spec_files=${spec_files}" >> "${GITHUB_OUTPUT}"

  lint:
    needs:
      - list_spec_files
    strategy:
      fail-fast: false
      matrix:
        spec_file: ${{ fromJson(needs.list_spec_files.outputs.spec_files) }}
    runs-on: ubuntu-24.04
    container: ${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
    env:
      SPEC_FILE: SPECS/${{ matrix.spec_file }}
    steps:
      - run: dnf --assumeyes install git epel-release
      - run: dnf --assumeyes install rpmlint
      - uses: actions/checkout@v5
      - run: rpmlint "${SPEC_FILE}"
