---
name: pipeline
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      gpg_key_id:
        required: true
        type: string
      gpg_public_key:
        required: true
        type: string
      gpg_public_keyring:
        required: true
        type: string
      build_with_published_repository:
        required: false
        type: boolean
        default: false
      targets:
        required: false
        type: string
        default: |
          [
            {"codename": "el9", "docker_image_name": "ghcr.io/almalinux/9-base", "docker_image_tag": "9", "runner_image": "ubuntu-24.04", "architecture": "x86_64"},
            {"codename": "el9", "docker_image_name": "ghcr.io/almalinux/9-base", "docker_image_tag": "9", "runner_image": "ubuntu-24.04-arm", "architecture": "aarch64"},
            {"codename": "el10", "docker_image_name": "ghcr.io/almalinux/10-base", "docker_image_tag": "10", "runner_image": "ubuntu-24.04", "architecture": "x86_64"},
            {"codename": "el10", "docker_image_name": "ghcr.io/almalinux/10-base", "docker_image_tag": "10", "runner_image": "ubuntu-24.04-arm", "architecture": "aarch64"}
          ]
      publish:
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    uses: ./.github/workflows/lint.yml
    with:
      codename: ${{ matrix.target.codename }}
      docker_image_name: ${{ matrix.target.docker_image_name }}
      docker_image_tag: ${{ matrix.target.docker_image_tag }}
      runner_image: ${{ matrix.target.runner_image }}

  build:
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    uses: ./.github/workflows/build.yml
    with:
      codename: ${{ matrix.target.codename }}
      docker_image_name: ${{ matrix.target.docker_image_name }}
      docker_image_tag: ${{ matrix.target.docker_image_tag }}
      runner_image: ${{ matrix.target.runner_image }}
      gpg_key_id: ${{ inputs.gpg_key_id }}
      gpg_public_key: ${{ inputs.gpg_public_key }}
      build_with_published_repository: ${{ inputs.build_with_published_repository }}
      sign: ${{ inputs.publish }}
    secrets: inherit

  publish:
    if: inputs.publish
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    uses: ./.github/workflows/publish.yml
    with:
      docker_image_name: ${{ matrix.target.docker_image_name }}
      docker_image_tag: ${{ matrix.target.docker_image_tag }}
      runner_image: ${{ matrix.target.runner_image }}
      architecture: ${{ matrix.target.architecture }}
      gpg_public_key: ${{ inputs.gpg_public_key }}
      gpg_public_keyring: ${{ inputs.gpg_public_keyring }}
    secrets: inherit
